backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  
media_folder: "/assets/media"
public_folder: "/assets/media"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  